# Generated by Django 5.0 on 2024-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaryapp', '0002_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
