# Generated by Django 5.0 on 2024-09-17 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaryapp', '0003_patients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='Icd_details',
            fields=[
                ('icd_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_id', models.IntegerField()),
                ('icd_number', models.CharField(max_length=50)),
                ('icd_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'tbl_icd_details',
            },
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('sub_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_sub_category',
            },
        ),
    ]
