# Generated by Django 5.0 on 2024-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaryapp', '0005_prescription_icd_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='icd_details_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
