# Generated by Django 5.0 on 2024-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaryapp', '0006_alter_prescription_icd_details_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
