# Generated by Django 5.0 on 2024-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaryapp', '0007_appointment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='amount',
            new_name='fee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pay_status',
            field=models.CharField(default='Not Paid', max_length=50),
        ),
    ]
