# Generated by Django 5.0 on 2024-09-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaryapp', '0008_rename_amount_appointment_fee_appointment_pay_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Icd_details',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='icd_details_id',
        ),
    ]
